version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: SalesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

volumes:
  my_dbdata: